services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/chiselpigs.co.uk:/etc/letsencrypt/live/chiselpigs.co.uk
  scrum-poker:
    image: axeleroy/self-host-planning-poker:latest
    ports:
      - 8000:8000
    volumes:
      - planning-poker-data:/data
    environment:
      - APP_ROOT=/scrum-poker/

volumes:
  planning-poker-data: {}
